fix(husky): fixed the way to format cs files

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,32 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-# Navegamos al directorio raíz del proyecto
 cd "$(dirname "$0")/.."
 
-dotnet restore --verbosity quiet
-dotnet format Tienda-UCN-api.csproj --verify-no-changes --verbosity quiet
+# Verificamos el formato de los archivos stageados en git con extension de .cs
+STAGED_CS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.cs$" || true)
 
-echo "Runeando el pre commit"
+if [ -n "$STAGED_CS_FILES" ]; then
+    echo "Formateando archivos"
+    # Convertir lista de archivos a parámetros separados por espacio
+    FILES_LIST=""
+    for file in $STAGED_CS_FILES; do
+        FILES_LIST="$FILES_LIST $file"
+    done
+    dotnet format --include$FILES_LIST --verbosity normal
+    FORMAT_EXIT_CODE=$?
+
+    if [ $FORMAT_EXIT_CODE -ne 0 ]; then
+        echo "Error en el formateo: $FORMAT_EXIT_CODE"
+        exit 1
+    fi
+
+    # Re-stagear archivos formateados
+    git add $STAGED_CS_FILES
+    echo "Archivos formateados añadidos al stage area"
+else
+    echo "No hay archivos de C# que formatear"
+fi
+
+
+echo "✅ Pre-commit checks passed!"
